import React, {useEffect, useRef, useState} from 'react';
import {motion, useReducedMotion} from 'framer-motion';
import {Sparkles} from 'lucide-react';
import heroDemos from './hero-demos.manifest.json';

/**
 * StackedWidgetCarousel — hero visual: a stack of REAL recorded demos of
 * diverse client landing pages, each running the actual ElevenLabs widget
 * being chatted with (recorded via the auto_demo Playwright runner against
 * per-vertical agents). The front card holds focus with a glowing border
 * tracer; back cards step away with scale + blur + opacity. A radial vignette
 * fades the deck into the page so the stack reads as extending into the
 * background. Cards auto-lap on an interval.
 *
 * Source assets + agent ids live in client/public/assets/hero-demos/ and are
 * regenerated by `bun run script/record-hero-demos.ts`. See docs/hero-demo-plan.md.
 *
 * Round-2 feedback F002 (homepage) and F013 (/products/websites).
 */

type HeroDemo = {
  id: string;
  brand: string;
  tagline: string;
  caption: string;
  video: string;
  poster: string;
  agentId: string;
};

const DEMOS = heroDemos as HeroDemo[];
const DECK_INTERVAL_MS = 6500;

type StackedWidgetCarouselProps = {
  isDark: boolean;
  /** Heading shown above the deck. */
  caption: string;
  /** Subtle subheading. */
  subcaption: string;
};

export default function StackedWidgetCarousel({
  isDark,
  caption,
  subcaption,
}: StackedWidgetCarouselProps) {
  const [frontIndex, setFrontIndex] = useState(0);
  const reduceMotion = useReducedMotion();
  // Container size drives the SVG glow-tracer path on the front card.
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- React refs use null sentinel; converting to undefined breaks RefObject<HTMLDivElement> consumers.
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [dim, setDim] = useState({w: 0, h: 0});

  useEffect(() => {
    if (reduceMotion || DEMOS.length < 2) return;
    const id = globalThis.setInterval(() => {
      setFrontIndex((i) => (i + 1) % DEMOS.length);
    }, DECK_INTERVAL_MS);
    return () => {
      globalThis.clearInterval(id);
    };
  }, [reduceMotion]);

  useEffect(() => {
    if (!containerRef.current) return;
    const update = () => {
      if (!containerRef.current) return;
      const r = containerRef.current.getBoundingClientRect();
      setDim({w: r.width, h: r.height});
    };

    update();
    const obs = new ResizeObserver(update);
    obs.observe(containerRef.current);
    return () => {
      obs.disconnect();
    };
  }, []);

  const {w, h} = dim;
  const tracerD =
    w > 0
      ? `M 24 1 L ${w - 4} 1 Q ${w - 1} 1 ${w - 1} 4 L ${w - 1} ${h - 24} Q ${w - 1} ${h - 1} ${w - 24} ${h - 1} L 4 ${h - 1} Q 1 ${h - 1} 1 ${h - 4} L 1 24 Q 1 1 24 1 Z`
      : '';

  return (
    <div
      ref={containerRef}
      className="relative h-[420px] md:h-[480px] w-full"
      data-testid="stacked-widget-carousel"
    >
      {DEMOS.map((demo, i) => {
        const offset = (i - frontIndex + DEMOS.length) % DEMOS.length;
        const isFront = offset === 0;
        const z = DEMOS.length - offset;
        const translateY = -offset * 14;
        const scale = 1 - offset * 0.06;
        const opacity = isFront ? 1 : Math.max(0.18, 0.7 - offset * 0.18);
        const blur = offset * 1.5;
        return (
          <motion.div
            key={demo.id}
            initial={false}
            animate={{
              y: translateY,
              scale,
              opacity,
              filter: `blur(${blur}px)`,
            }}
            transition={{type: 'spring', stiffness: 60, damping: 18}}
            style={{zIndex: z}}
            className="absolute inset-0"
            aria-hidden={!isFront}
          >
            <DemoCard
              demo={demo}
              isDark={isDark}
              isFront={isFront}
              tracerD={tracerD}
            />
          </motion.div>
        );
      })}

      {/* Vignette mask: fades the deck into the surrounding page so the
          stack reads as extending out into the background. */}
      <div
        className="pointer-events-none absolute inset-0 z-50"
        style={{
          background: isDark
            ? 'radial-gradient(ellipse at center, transparent 30%, rgba(18,17,26,0.55) 78%, rgba(18,17,26,0.92) 100%)'
            : 'radial-gradient(ellipse at center, transparent 30%, rgba(252,250,245,0.55) 78%, rgba(252,250,245,0.92) 100%)',
        }}
      />

      {/* Caption strip below the deck */}
      <div className="pointer-events-none absolute inset-x-0 -bottom-1 z-[60] flex flex-col items-center gap-1 pb-1">
        <div className="mono-font text-[10px] uppercase tracking-widest text-[var(--s500)] flex items-center gap-2">
          <span className="h-1.5 w-1.5 rounded-full bg-[var(--s500)] animate-pulse" />
          {caption}
        </div>
        <div className="text-[11px] opacity-60 leading-snug max-w-md text-center">
          {subcaption}
        </div>
      </div>
    </div>
  );
}

function DemoCard({
  demo,
  isDark,
  isFront,
  tracerD,
}: {
  demo: HeroDemo;
  isDark: boolean;
  isFront: boolean;
  tracerD: string;
}) {
  const reduceMotion = useReducedMotion();
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- video ref uses the null sentinel React assigns.
  const videoRef = useRef<HTMLVideoElement | null>(null);

  // Only the front card plays; back cards hold their poster to save CPU.
  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    if (isFront && !reduceMotion) {
      v.currentTime = 0;
      void v.play().catch(() => undefined);
    } else {
      v.pause();
    }
  }, [isFront, reduceMotion]);

  return (
    <div
      className={`relative h-full w-full overflow-hidden rounded-[20px_4px_20px_4px] border ${
        isDark ? 'border-white/10 bg-[#15141d]' : 'border-black/10 bg-white'
      }`}
      style={{boxShadow: 'var(--shadow-card)'}}
    >
      {/* Animated glow-tracer — only the front card runs it. */}
      {isFront && tracerD ? (
        <div className="absolute inset-0 pointer-events-none z-30">
          <svg className="absolute inset-0 h-full w-full overflow-visible">
            <motion.path
              d={tracerD}
              fill="none"
              stroke="var(--s500)"
              strokeWidth="2"
              strokeDasharray="120 1600"
              strokeLinecap="round"
              initial={{strokeDashoffset: 0}}
              animate={{strokeDashoffset: -1720}}
              transition={{duration: 4.2, repeat: Infinity, ease: 'linear'}}
            />
          </svg>
        </div>
      ) : null}

      <video
        ref={videoRef}
        className="h-full w-full object-cover object-top"
        src={demo.video}
        poster={demo.poster}
        muted
        loop
        playsInline
        preload={isFront ? 'auto' : 'metadata'}
        aria-label={`${demo.brand} — live ElevenLabs agent demo`}
      />

      {/* Brand + caption chip overlaid on the recording */}
      <div className="pointer-events-none absolute left-3 top-3 z-20 flex flex-col gap-1">
        <span
          className={`mono-font text-[9px] uppercase tracking-widest rounded-full px-2 py-1 backdrop-blur ${
            isDark ? 'bg-black/45 text-white/85' : 'bg-white/70 text-[#12111a]'
          }`}
        >
          {demo.caption}
        </span>
      </div>
    </div>
  );
}

export function StackedWidgetCarouselBadge() {
  return (
    <span className="inline-flex items-center gap-1 mono-font text-[10px] uppercase tracking-widest text-[var(--s500)]">
      <Sparkles size={11} className="sarah-glimmer" aria-hidden />
      Live across client sites
    </span>
  );
}
