import React, {useEffect, useRef, useState} from 'react';
import {motion, useReducedMotion} from 'framer-motion';
import {Sparkles} from 'lucide-react';
import heroDemos from './hero-demos.manifest.json';

/**
 * HexDemoGrid — hero visual: a hexagonal fish-scale grid of client demos that
 * recedes into 3D depth and blends transparently into the page (no vignette).
 * The center hex holds the focus demo (a REAL recorded ElevenLabs widget
 * conversation on a client landing page); two concentric rings peek behind it,
 * the inner ring carrying the other recorded demos and the outer ring fading
 * into generic "node" tiles. On each rotation the next demo ejects forward from
 * behind the stack to the focus position while a circuit-tracer pulse fans out
 * from the center along the hex edges.
 *
 * Source assets + agent ids live in client/public/assets/hero-demos/ and are
 * regenerated by `bun run script/record-hero-demos.ts`. Default export name is
 * kept (StackedWidgetCarousel) so App.tsx + websites.tsx call sites are stable.
 *
 * Round-3 feedback R3-F001.
 */

type HeroDemo = {
  id: string;
  brand: string;
  tagline: string;
  caption: string;
  video: string;
  poster: string;
  agentId: string;
};

const DEMOS = heroDemos as HeroDemo[];
const ROTATE_MS = 5200;
const HEX_W = 210; // pointy-top hex bounding width
const HEX_H = 188;

// Axial → pixel for pointy-top hexes; spacing tuned so tiles overlap
// (fish-scale) rather than tile flush.
function axialToXY(q: number, r: number) {
  const x = HEX_W * 0.8 * (q + r / 2);
  const y = HEX_H * 0.68 * r;
  return {x, y};
}

// Ring slots: center + ring-1 (6) + ring-2 (12). Each carries a depth tier
// (0 nearest → 2 farthest) that drives scale / blur / opacity / z-translate.
type Slot = {q: number; r: number; ring: 0 | 1 | 2};

function buildSlots(): Slot[] {
  const slots: Slot[] = [{q: 0, r: 0, ring: 0}];
  const ring1: Array<[number, number]> = [
    [1, 0],
    [0, 1],
    [-1, 1],
    [-1, 0],
    [0, -1],
    [1, -1],
  ];
  for (const [q, r] of ring1) slots.push({q, r, ring: 1});
  // Ring 2: walk the 12 outer cells.
  const ring2: Array<[number, number]> = [
    [2, 0],
    [1, 1],
    [0, 2],
    [-1, 2],
    [-2, 2],
    [-2, 1],
    [-2, 0],
    [-1, -1],
    [0, -2],
    [1, -2],
    [2, -2],
    [2, -1],
  ];
  for (const [q, r] of ring2) slots.push({q, r, ring: 2});
  return slots;
}

const SLOTS = buildSlots();
// Decorative node tiles fill every slot that isn't carrying a live demo.
const DECO_SEED = [0.62, 0.31, 0.84, 0.17, 0.95, 0.45, 0.73, 0.08, 0.55];

type StackedWidgetCarouselProps = {
  isDark: boolean;
  /** Retained for call-site compatibility; no longer rendered (R3-F001.6). */
  caption?: string;
  /** Retained for call-site compatibility; no longer rendered (R3-F001.6). */
  subcaption?: string;
};

export default function StackedWidgetCarousel({
  isDark,
}: StackedWidgetCarouselProps) {
  const [front, setFront] = useState(0);
  const [pulse, setPulse] = useState(0);
  const reduceMotion = useReducedMotion();

  useEffect(() => {
    if (reduceMotion || DEMOS.length < 2) return;
    const id = globalThis.setInterval(() => {
      setFront((i) => (i + 1) % DEMOS.length);
      setPulse((p) => p + 1);
    }, ROTATE_MS);
    return () => {
      globalThis.clearInterval(id);
    };
  }, [reduceMotion]);

  return (
    <div
      className="relative h-[420px] md:h-[480px] w-full overflow-visible"
      data-testid="stacked-widget-carousel"
      style={{perspective: '1400px'}}
    >
      <CircuitTracers
        isDark={isDark}
        pulse={pulse}
        reduceMotion={Boolean(reduceMotion)}
      />

      <div
        className="absolute inset-0"
        style={{transformStyle: 'preserve-3d'}}
        aria-label="Live client demos across diverse businesses"
      >
        {SLOTS.map((slot, slotIndex) => {
          // The center slot always shows the current front demo; the two
          // nearest ring-1 slots show the upcoming demos. Everything else is a
          // decorative node tile that fades into the page.
          const {x, y} = axialToXY(slot.q, slot.r);
          const demoIndex =
            slot.ring === 0
              ? front
              : slotIndex <= DEMOS.length - 1
                ? (front + slotIndex) % DEMOS.length
                : -1;
          const demo = demoIndex >= 0 ? DEMOS[demoIndex] : undefined;
          const tier = slot.ring;
          const scale = [1, 0.78, 0.58][tier];
          const z = [0, -180, -380][tier];
          const opacity = demo ? (tier === 0 ? 1 : 0.9) : [1, 0.5, 0.26][tier];
          const blur = [0, 1, 2.4][tier];
          return (
            <motion.div
              key={`${slot.q}.${slot.r}`}
              className="absolute left-1/2 top-1/2"
              style={{zIndex: 100 - tier * 10}}
              initial={false}
              animate={{
                x: x - HEX_W / 2,
                y: y - HEX_H / 2,
                scale,
                z,
                opacity,
                filter: `blur(${blur}px)`,
              }}
              transition={{type: 'spring', stiffness: 64, damping: 17}}
              aria-hidden={slot.ring !== 0}
            >
              {demo ? (
                <HexDemoTile
                  demo={demo}
                  isFront={slot.ring === 0}
                  isDark={isDark}
                  reduceMotion={Boolean(reduceMotion)}
                />
              ) : (
                <HexNodeTile
                  isDark={isDark}
                  seed={DECO_SEED[slotIndex % DECO_SEED.length]}
                />
              )}
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}

// Clip path for a pointy-top hexagon.
const HEX_CLIP =
  'polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)';

function HexDemoTile({
  demo,
  isFront,
  isDark,
  reduceMotion,
}: {
  demo: HeroDemo;
  isFront: boolean;
  isDark: boolean;
  reduceMotion: boolean;
}) {
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- video ref uses React's null sentinel.
  const videoRef = useRef<HTMLVideoElement | null>(null);

  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    if (isFront && !reduceMotion) {
      v.currentTime = 0;
      void v.play().catch(() => undefined);
    } else {
      v.pause();
    }
  }, [isFront, reduceMotion]);

  return (
    <div className="relative" style={{width: HEX_W, height: HEX_H}}>
      {/* Pulsing circuit border — sits just outside the clipped media. */}
      <div
        className="absolute -inset-[3px] z-0"
        style={{
          clipPath: HEX_CLIP,
          background: isFront
            ? 'conic-gradient(from 0deg, var(--s500), var(--v500), var(--s500))'
            : isDark
              ? 'rgba(255,255,255,0.12)'
              : 'rgba(0,0,0,0.12)',
          animation:
            isFront && !reduceMotion ? 'hex-spin 5.2s linear infinite' : 'none',
        }}
      />
      <div
        className="absolute inset-0 overflow-hidden"
        style={{
          clipPath: HEX_CLIP,
          background: isDark ? '#15141d' : '#fff',
        }}
      >
        <video
          ref={videoRef}
          className="h-full w-full object-cover object-center"
          src={demo.video}
          poster={demo.poster}
          muted
          loop
          playsInline
          preload={isFront ? 'auto' : 'metadata'}
          aria-label={`${demo.brand} — live agent demo`}
        />
      </div>
    </div>
  );
}

function HexNodeTile({isDark, seed}: {isDark: boolean; seed: number}) {
  // A decorative "node" hex: faint UI-glyph lines + a soft glowing rim. These
  // fill the outer rings so the live demos read as part of an endless mesh.
  return (
    <div style={{width: HEX_W, height: HEX_H}} className="relative">
      <div
        className="absolute inset-0"
        style={{
          clipPath: HEX_CLIP,
          border: isDark
            ? '1px solid rgba(255,255,255,0.16)'
            : '1px solid rgba(0,0,0,0.12)',
          background: isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.025)',
        }}
      />
      <div
        className="absolute inset-0 flex flex-col items-center justify-center gap-1.5"
        style={{clipPath: HEX_CLIP}}
        aria-hidden
      >
        <span
          className="h-1.5 w-1.5 rounded-full"
          style={{
            background: 'var(--s500)',
            opacity: 0.4 + seed * 0.4,
            boxShadow: '0 0 8px var(--s500)',
          }}
        />
        <span
          className="h-[3px] rounded-full bg-current opacity-20"
          style={{width: 28 + seed * 26}}
        />
        <span
          className="h-[3px] rounded-full bg-current opacity-10"
          style={{width: 18 + seed * 18}}
        />
      </div>
    </div>
  );
}

function CircuitTracers({
  isDark,
  pulse,
  reduceMotion,
}: {
  isDark: boolean;
  pulse: number;
  reduceMotion: boolean;
}) {
  // Six straight "circuit" runs from the center node out to each ring-1 node.
  // On each rotation (pulse change) a bright dash travels center→edge.
  const center = {x: 50, y: 50};
  const ring1 = SLOTS.filter((s) => s.ring === 1).map((s) =>
    axialToXY(s.q, s.r),
  );
  // Normalize the ring-1 pixel offsets into the 100x100 viewBox space.
  const spread = 30;
  const lines = ring1.map(({x, y}) => ({
    x2: center.x + (x / (HEX_W * 0.82)) * spread,
    y2: center.y + (y / (HEX_H * 0.7)) * spread,
  }));

  return (
    <svg
      className="pointer-events-none absolute inset-0 h-full w-full z-[5] overflow-visible"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid meet"
      aria-hidden
    >
      {lines.map((l, i) => (
        <g key={i} data-tracer="run">
          <line
            x1={center.x}
            y1={center.y}
            x2={l.x2}
            y2={l.y2}
            stroke={isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.06)'}
            strokeWidth="0.4"
          />
          {reduceMotion ? null : (
            <line
              key={`pulse-${pulse}-${i}`}
              x1={center.x}
              y1={center.y}
              x2={l.x2}
              y2={l.y2}
              stroke="var(--s500)"
              strokeWidth="0.7"
              strokeLinecap="round"
              strokeDasharray="6 40"
              style={{
                animation: `tracer-fan 1.1s ease-out`,
                filter: 'drop-shadow(0 0 2px var(--s500))',
              }}
            />
          )}
        </g>
      ))}
    </svg>
  );
}

export function StackedWidgetCarouselBadge() {
  return (
    <span className="inline-flex items-center gap-1 mono-font text-[10px] uppercase tracking-widest text-[var(--s500)]">
      <Sparkles size={11} className="sarah-glimmer" aria-hidden />
      Voice agents, live on the page
    </span>
  );
}
